config/routes.rb
Ploxr::Application.routes.draw do
  resources :chapters, :path => "chapter"
  resources :pages,    :path => "page"
  resources :books,    :path => "book"   
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :books, :chapters, :pages
  end
  root 'static_pages#home'
  match '/about',       to: 'static_pages#about', via: 'get'
  match '/subscribe',   to: 'pages#feed',         via: 'get', as: :feed, defaults: { format: 'atom' }
  match '/signin',      to: 'sessions#new',       via: 'get'
  match '/signout',     to: 'sessions#destroy',   via: 'delete'
  match '/admin/home',  to: 'admin/books#index',  via: 'get'
  match '/admin',       to: 'admin/books#index',  via: 'get'
 

  

end

app/views/admin/pages/edit.html.erb
<% provide(:title, "Edit Page #{@page.position} of Chapter #{@chapter.position}") %>

<div class="book">
<h1>Edit Page <%= @page.position %> of Chapter <%= @chapter.position %></h1>
    <%= form_for [:admin, @page], url: admin_page_path(@page.id) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="row image_area">
        <div class="span3">
        <%= image_tag @page.image.url(:medium),
                      class: "image_preview img-rounded pull-left" %>
        </div>

        <div class="span5">
          <label>File</label>
          <p><%= @page.image_file_name %></p>

          <label>Size</label>
          <p><%= number_to_human_size(@page.image_file_size) %></p>

          <label>Upload a different image:</label>
          <%= f.file_field :image %>
        </div>
      </div>

      <div class="object_meta">

        <%= f.label      :title %>
        <%= f.text_field :title %>
        <p class="muted"><small>Short and sweet.</small><p>

        <%= f.label 		 :description %>
        <%= f.text_area  :description %>

        <%= f.label			 :position, "Position in chapter" %>
        <%= f.select     :position, (1..@chapter.pages.size) %>

        <div class="buttons">
        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
        <%= link_to "Cancel", admin_path, class: "cancel" %>
        </div>

      </div>
    <% end %>

    <div class="delete_wrapper well">
      <%= link_to "<i class='icon-trash icon-white'></i> DELETE PAGE".html_safe, 
                  admin_page_path(@page.id),
                  method: :delete,
                  data: { confirm: "Hey man, you sure?" },
                  title: "Delete Page #{@page.position}?",
                  class: "btn btn-big btn-delete pull-right" %>
    </div>
  </div>
</div>

app/views/admin/pages/new.html.erb
<% provide(:title, "Add a Page to Chapter #{@chapter.position}") %>

<div class="book">
<h1>Add a Page to Chapter <%= @chapter.position %></h1>

    <%= form_for [:admin, @page] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="row image_area">
        <div class="span3">
        <%= image_tag @page.image.url(:medium),
                      class: "image_preview img-rounded pull-left" %>
        </div>

        <div class="span5">
          <label>File</label>
          <p><%= @page.image_file_name %></p>

          <label>Size</label>
          <p><%= number_to_human_size(@page.image_file_size) %></p>

          <label>Upload a different image:</label>
          <%= f.file_field :image %>
        </div>
      </div>

      <div class="object_meta">

        <%= f.label      :title %>
        <%= f.text_field  :title %>
        <p class="muted"><small>Short and sweet.</small><p>

        <%= f.label 		 :description %>
        <%= f.text_area  :description %>

        <%= f.hidden_field(:chapter_id, value: @page.chapter_id) %>

        <%= f.label			 :position, "Position in chapter" %>
        <p class="muted"><small>New pages are automatically last in the chapter.</small><p>
        <%= f.hidden_field(:position, value: @page.position) %>

        <div class="buttons">
        <%= f.submit "Add Page", class: "btn btn-large btn-primary" %>
        <%= link_to "Cancel", admin_path %>
        </div>

      </div>
    <% end %>
</div>