config/routes.rb
Ploxr::Application.routes.draw do
  resources :chapters, :path => "chapter"
  resources :pages,    :path => "page"
  resources :books,    :path => "book"   
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :books, :chapters, :pages
  end
  root 'static_pages#home'
  match '/about',       to: 'static_pages#about', via: 'get'
  match '/subscribe',   to: 'pages#feed',         via: 'get', as: :feed, defaults: { format: 'atom' }
  match '/signin',      to: 'sessions#new',       via: 'get'
  match '/signout',     to: 'sessions#destroy',   via: 'delete'
  match '/admin/home',  to: 'admin/books#index',  via: 'get'
  match '/admin',       to: 'admin/books#index',  via: 'get'
 

  

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many  :chapters, -> { order(:position) }
	validates :title, 				presence: true
	validates :description, 	presence: true
	validates :blurb,					presence: true
	validates :author, 				presence: true
	validates :author_about,	presence: true

	has_attached_file :cover, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::BaseController
	
	def index
		@book = Book.first
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		if @book.update_attributes(book_params)
      flash[:success] = "Book updated"
      redirect_to admin_path
    else
      render 'edit'
    end
	end

	private

		def book_params
	    params.require(:book).permit(:title, :description, :blurb, :author, :author_about, :cover)
	  end

end

app/views/admin/books/edit.html.erb
<% provide(:title, 'Edit Book') %>

<div class="book">
  <h1>Edit Book</h1>

      <%= form_for [:admin, @book] do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <div class="row image_area">
          <div class="span3">
          <%= image_tag @book.cover.url(:medium), 
                        class: "image_preview img-rounded pull-left" %>
          </div>
          <div class="span5">
            
            <label>File</label>
            <p><%= @book.cover_file_name %></p>
            
            <label>Size</label>
            <p><%= number_to_human_size(@book.cover_file_size) %></p>

            <label>Upload a different cover:</label>
              <%= f.file_field :cover, width: "100" %>
          </div>
        </div>

        <div class="object_meta">

          <%= f.label :title %>
          <%= f.text_field :title %>

          <%= f.label :description %>
          <%= f.text_area :description %>

          <%= f.label :blurb %>
          <%= f.text_area :blurb %>

          <%= f.label :author %>
          <%= f.text_field :author %>

          <%= f.label :author_about %>
          <%= f.text_area :author_about %>

          <div class="buttons">
          <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
          <%= link_to "Cancel", admin_path %>
        </div>

      </div>
      <% end %>

</div>

app/views/admin/books/index.html.erb
<% provide(:title, 'Admin') %>

<div class="book">
			
	<%= image_tag @book.cover.url(:medium), 
	     class: "image_preview img-rounded pull-left" %>

	<h1>PLOX</h1>

	<h2><%= @book.title %></h2>

	<p><%= link_to "<i class='icon-wrench icon-white'></i> EDIT".html_safe, 	
								 edit_admin_book_path(@book.id),
								 title: "Edit the cover and contents of this book.",
								 class: "btn btn-small" %></p>

	<p><%= simple_format(@book.blurb) %></p>

	<div id="book_more" class="collapse">
		<h3>Description</h3>
		<p><%= simple_format(@book.description) %></p>
		<h3>About the author, <%= @book.author %></h3>
		<p><%= simple_format(@book.author_about) %></p>
	</div>

	<a class="more pull-right" data-toggle="collapse" data-target="#book_more">
		<i class='icon-resize-vertical icon-white'></i> MORE
	</a>

	<div class="contents accordion" id="accordion2">	

		<% @book.chapters.each do |chapter| %>

		 <div class="accordion-group">
			<div class="accordion-heading">

				<%= link_to "<i class='icon-wrench icon-white'></i>".html_safe, 
										edit_admin_chapter_path(chapter.id),
										title: "Edit Chapter #{chapter.title}", 
										class: "btn btn-mini pull-right edit-chapter" %>

				<a class="accordion-toggle" data-toggle="collapse" 
				   data-parent="#accordion2" href="#collapse<%= chapter.id %>">
					 Chapter <%= chapter.position %>: <%= chapter.title %>
				</a> 

	 		</div><!-- /accordion-heading -->

	 		<% if chapter.last? %>
	 			<div id="collapse<%= chapter.id %>" class="accordion-body collapse in">
	 		<% else %>
				<div id="collapse<%= chapter.id %>" class="accordion-body collapse">
	 		<% end %>

	 			<div class="accordion-inner">
					<ul class="inline comic-pages">
							<% chapter.pages.each do |page| %>
								<li>
									<%= link_to image_tag(page.image.url(:thumb), 
                      				class: "img-rounded"),
                      				edit_admin_page_path(page.id),
                      				title: "Edit Page #{page.position}" %>
                </li>
							<% end %>

							<li>
								<%= link_to "<i class='icon-plus icon-white'></i>".html_safe, 
										        new_admin_page_path(:chapter_id => chapter.id),
										        class: "btn btn-big add-page" %>
							</li>

					</ul>
				</div><!-- /accordion-inner -->

			</div><!-- /#collapse -->
		</div><!-- /accordion-group -->
		<% end %>
	</div><!-- /contents -->
	<%= link_to "<i class='icon-plus icon-white'></i> ADD A CHAPTER".html_safe, new_admin_chapter_path, class: "btn btn-big" %>
</div>