config/routes.rb
Ploxr::Application.routes.draw do
  resources :chapters, :path => "chapter"
  resources :pages,    :path => "page"
  resources :books,    :path => "book"   
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :books, :chapters, :pages
  end
  root 'static_pages#home'
  match '/about',       to: 'static_pages#about', via: 'get'
  match '/subscribe',   to: 'pages#feed',         via: 'get', as: :feed, defaults: { format: 'atom' }
  match '/signin',      to: 'sessions#new',       via: 'get'
  match '/signout',     to: 'sessions#destroy',   via: 'delete'
  match '/admin/home',  to: 'admin/books#index',  via: 'get'
  match '/admin',       to: 'admin/books#index',  via: 'get'
 

  

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	belongs_to :book
	acts_as_list scope: :book
	acts_as_url :title, :sync_url => true

	has_many 	 :pages, -> { order(:position) }, dependent: :destroy

	validates	 :position,			presence: true
	validates  :title, 				presence: true
	validates  :description, 	presence: true
	validates  :book_id, 			presence: true

  def full_chapter_title
    "#{position}: #{title}"
  end

  def to_param
  	url
	end
end

app/controllers/admin/chapters_controller.rb
class Admin::ChaptersController < Admin::BaseController
	
	def index
	end

	def new
		@chapter = Chapter.new
		@chapter.position = Book.last.chapters.size + 1
	end

	def create
		@chapter = Chapter.new(chapter_params)
		@chapter.book_id = 1
		@chapter.title = "#{chapter_params[:name]}"
		if @chapter.save
			flash[:success] = "Chapter created!"
			redirect_to admin_path
		else
			render 'new'
		end
	end

	def edit
		@chapter = Chapter.find(params[:id])
	end

	def update
		@chapter = Chapter.find(params[:id])
		@chapter.title = "#{chapter_params[:name]}"
		if @chapter.update_attributes(chapter_params)
			flash[:success] = "Chapter updated"
			redirect_to admin_path
		else
			render 'edit'
		end
	end

	def destroy
		chapter = Chapter.find(params[:id])
		chapter.destroy
		flash[:success] = "Chapter deleted."
		redirect_to admin_path
	end

	private

		def chapter_params
			params.require(:chapter).permit(:title, :description, :position, :name)
		end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

	def show
		@chapters = Book.last.chapters.order("position ASC")
		@page = Chapter.find_by_url(params[:id]).pages.order("position ASC").first
		@chapter = Chapter.find_by(id: @page.chapter_id)
	end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/admin/chapters/edit.html.erb
<% provide(:title, "Edit Chapter #{@chapter.position}: #{@chapter.title}") %>

<div class="book">
<h1>Edit Chapter <%= @chapter.position %>: <%= @chapter.title %></h1>

    <%= form_for [:admin, @chapter], url: admin_chapter_path(@chapter.id) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label 		 :name %>
      <%= f.text_field :name %>

      <%= f.label 		 :description %>
      <%= f.text_area  :description %>

      <%= f.label      :position %>
      <%= f.select     :position, (1..Book.last.chapters.size) %>

      <div class="buttons">
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
      <%= link_to "Cancel", admin_path %>
    	</div>
    <% end %>

    <div class="delete_wrapper well">
      <%= link_to "<i class='icon-trash icon-white'></i> DELETE CHAPTER".html_safe, 
                  admin_chapter_path(@chapter.id),
                  method: :delete,
                  data: { confirm: "Hey man, you sure? This will delete all the pages in this chapter, too!" },
                  title: "Delete #{@chapter.title} and all its pages?",
                  class: "btn btn-big btn-delete pull-right" %>
    </div>

</div>

app/views/admin/chapters/new.html.erb
<% provide(:title, "Add Chapter #{@chapter.position}") %>

<div class="book">
<h1>Add Chapter <%= @chapter.position %></h1>
<p class="muted"><small>New chapters are automatically last in the book.</small><p>

    <%= form_for [:admin, @chapter] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label 		 :name %>
      <%= f.text_field :name %>
      <p class="muted"><small>Example: "The Storm", not "Chapter 4: The Storm".</small><p>

      <%= f.label 		 :description %>
      <%= f.text_area  :description %>

      <%= f.hidden_field(:position, value: @chapter.position) %>

      <div class="buttons">
      <%= f.submit "Create Chapter", class: "btn btn-large btn-primary" %>
      <%= link_to "Cancel", admin_path %>
      </div>
    <% end %>
</div>