config/routes.rb
Ploxr::Application.routes.draw do
  resources :chapters, :path => "chapter"
  resources :pages,    :path => "page"
  resources :books,    :path => "book"   
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :books, :chapters, :pages
  end
  root 'static_pages#home'
  match '/about',       to: 'static_pages#about', via: 'get'
  match '/subscribe',   to: 'pages#feed',         via: 'get', as: :feed, defaults: { format: 'atom' }
  match '/signin',      to: 'sessions#new',       via: 'get'
  match '/signout',     to: 'sessions#destroy',   via: 'delete'
  match '/admin/home',  to: 'admin/books#index',  via: 'get'
  match '/admin',       to: 'admin/books#index',  via: 'get'
 

  

end

app/views/layouts/_admin_footer.html.erb
<footer>
	<div class="container">
		<div class="row">
		  <div class="span3 offset8">
		  		<h5>Powered by PLOXR&trade;</h5>
		  </div>
		</div><!-- /row -->
		<div class="row">
			<%= debug(params) if Rails.env.development? %>
		</div>
	</div><!-- /container -->
</footer>

app/views/layouts/_admin_header.html.erb
<header>
	<div class="navbar navbar-static-top">
			<div class="container">
				<span class="brand">ADMIN</span>
				<div class="nav-collapse collapse">
					<ul class="nav">
						<li><%= link_to "View site", root_path, target: '_blank' %></li>
					</ul>
				</div>

				<div class="nav-collapse collapse">
					<nav>
							<ul class="nav pull-right">
									<% if signed_in? %>
										<li class="greeting"><%= "Hi, #{current_user.first_name}!" %></li>
										<li class="signout"><%= link_to "Sign out", signout_path, method: "delete" %></li>
									<% end %>
							</ul>
					</nav>
				</div>

			</div>
	</div>
	<div class="container">
			<div class="admin_masthead"></div>
	</div>
</header>

app/views/layouts/_bottom_ads.html.erb
		<section>
			<div class="container rectangle_ads">
				<div class="row-fluid">
					<div class="span6">
							<!-- Plox_Lower_Rectangle_300X250 -->
							<div id='div-gpt-ad-1389238823574-1' style='width:300px; height:250px;'>
							<script type='text/javascript'>
							googletag.cmd.push(function() { googletag.display('div-gpt-ad-1389238823574-1'); });
							</script>
							</div>
					</div>
					<div class="span6">
							<!-- Plox_Upper_Rectangle_300X250 -->
							<div id='div-gpt-ad-1389238823574-2' style='width:300px; height:250px;'>
							<script type='text/javascript'>
							googletag.cmd.push(function() { googletag.display('div-gpt-ad-1389238823574-2'); });
							</script>
							</div>
					</div>
				</div>
			</div>
		</section>

app/views/layouts/_dfp_ads_js.html.erb
	  <!-- Google Ads -->
	  
	  <script type='text/javascript'>
			var googletag = googletag || {};
			googletag.cmd = googletag.cmd || [];
			(function() {
			var gads = document.createElement('script');
			gads.async = true;
			gads.type = 'text/javascript';
			var useSSL = 'https:' == document.location.protocol;
			gads.src = (useSSL ? 'https:' : 'http:') + 
			'//www.googletagservices.com/tag/js/gpt.js';
			var node = document.getElementsByTagName('script')[0];
			node.parentNode.insertBefore(gads, node);
			})();
		</script>

		<script type='text/javascript'>
			googletag.cmd.push(function() {
			googletag.defineSlot('/1051411/Plox_Leaderboard_728X90', [728, 90], 'div-gpt-ad-1389238823574-0').addService(googletag.pubads());
			googletag.defineSlot('/1051411/Plox_Lower_Rectangle_300X250', [300, 250], 'div-gpt-ad-1389238823574-1').addService(googletag.pubads());
			googletag.defineSlot('/1051411/Plox_Upper_Rectangle_300X250', [300, 250], 'div-gpt-ad-1389238823574-2').addService(googletag.pubads());
			googletag.enableServices();
			});
		</script>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
		<div class="row">
		  <div class="span6">
		  	<div id="blurb">
			    <h3><%= Book.last.title %></h3>
			    <%= simple_format(Book.last.blurb) %>
				</div>
			</div>
			<div class="span3">
				<div id="connect">
					<h3>Connect with Steve</h3>
					<div class="navbar">
				    <ul class="connect">
				    	<li class="connect_twitter">
				    		<%= link_to "Steve on Twitter", 
				    		            "https://twitter.com/SteveHamaker",
				    		            target: "_blank",
				    		            title:  "Steve on Twitter",
				    		            class: 	"outbound_link" %>
				      </li>
				    	<li class="connect_facebook">
				    		<%= link_to "PLOX on Facebook", 
				    		            "https://www.facebook.com/PloxComic",
				    		            target: "_blank",
				    		            title:  "PLOX on Facebook",
				    		            class: 	"outbound_link" %>
				    	</li>
				    	<li class="connect_rss">
				    		<%= link_to "PLOX RSS/Atom Feed", feed_path,
				    		            target: "_blank" %>
				    	</li>
				    </ul>
			  	</div>
				</div>
		  </div>
		  <div class="span3">
		  	<div id="share">
					<h3>Share this PLOX comic</h3>
					<div class="navbar">
						<ul class="nav share">
							<li>
								<%= link_to image_tag("facebook.png", alt: "Facebook"), 
								            "http://www.facebook.com/sharer/sharer.php?u=#{ request.original_url }",
								            target: "_blank",
								            title:  "Share on Facebook",
								            class: 	"outbound_link" %>
							</li>
							<li>
								<%= link_to image_tag("twitter.png", alt: "Twitter"), 
								            "http://twitter.com/intent/tweet?text=PLOX%20by%20@SteveHamaker%20#{ request.original_url }", 
								            target: "_blank",
								            title:  "Share on Twitter",
								            class:  "outbound_link" %>
							</li>
 							<li>
								<%= link_to image_tag("googleplus.png", alt: "Google+"), 
								            "https://plus.google.com/share?url=#{ request.original_url }", 
								            target: "_blank",
								            title:  "Share on Google+",
								            class: 	"outbound_link" %>
							</li>
						</ul>
					</div>
      	</div>
			</div>
		</div><!-- /row -->
		<div class="row">
			<%= debug(params) if Rails.env.development? %>
		</div>
	</div><!-- /container -->
</footer>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42540201-1', 'plox-comic.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_googleanalytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42540201-1', 'plox-comic.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<header>
	<div class="navbar navbar-static-top">
			<div class="container">
				<%= link_to "steve-hamaker.com", 'http://steve-hamaker.com',
																				 class: 'steve-hamaker' %>

 				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>

				<div class="nav-collapse collapse">
					<nav>
							<ul class="nav pull-right">
								<li><%= link_to "About", about_path %></li>
								<li><%= link_to "Subscribe", 
																"http://feeds.feedburner.com/plox-comic", 
																target: "_blank" %></li>
								<li><%= link_to "Support Plox:", 
																'http://www.patreon.com/plox',
																title:  "Support Plox at Patreon.com",
				    		            		class: 	"outbound_link", style: "display:inline;padding-right:7px;" %><%= link_to image_tag("patreon-logo.png", alt: "Patreon", width: "80px"), 
																'http://www.patreon.com/plox',
																title:  "Support Plox at Patreon.com",
				    		            		class: 	"outbound_link", style: "display:inline;padding:0;" %></li>
							</ul>
					</nav>
				</div>

			</div>
	</div>
	<%= render 'layouts/top_ad' if Rails.env.production? %>
	<div class="container">
		<%= link_to(root_path) do %>
			<div class="masthead"></div>
		<% end %>
	</div>
</header>

app/views/layouts/_sharethis.html.erb
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "987d9a40-2456-4be2-a206-2eebff37ddf7", doNotHash: true, doNotCopy: true, hashAddressBar: false});</script>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_top_ad.html.erb
	<div class="container" id="leaderboard">
		<!-- Plox_Leaderboard_728X90 -->				 
		<div id='div-gpt-ad-1389238823574-0' style='width:728px; height:90px;' >
			<script type='text/javascript'>
				googletag.cmd.push(function() { googletag.display('div-gpt-ad-1389238823574-0'); });
			</script>
		</div>
	</div>

app/views/layouts/_track_outbound_links.html.erb
<script type="text/javascript">
// Using jQuery Event API v1.3
$('.outbound_link').on('click', function() {
  ga('send', 'event', 'Outbound Link', 'click', this.getAttribute('href'));
});
</script>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">	
		<title>ADMIN : <%= full_title(yield(:title)) %></title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<meta name="Description"
			  content="PLOX: A comic about people who happen to be gamers.">
		<meta name="Author" content="Steve Hamaker">
		<meta name="Robots" content="noindex, nofollow"/>
		<%= csrf_meta_tags %>

		<!-- Stylesheets -->
		<%= stylesheet_link_tag    "application", media: "all", 
	  													 "data-turbolinks-track" => true %>

	  <%= render 'layouts/shim' %>

	  <!-- Javascripts -->
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

	  <!-- Fav and touch icons -->
	  <%= favicon_link_tag 'favicon.ico' %>
	  <%= favicon_link_tag 'favicon.ico', rel: 'apple-touch-icon', type: 'image/png' %>
	</head>
	<body class="admin">

		<%= render 'layouts/admin_header' %>

		<section>
			<div class="container admin_wrapper">
						<div class="content">

				      <% flash.each do |key, value| %>
				        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
				      <% end %>
							
							<%= yield %>
						</div>
			</div><!-- /container -->
		</section>

		<%= render 'layouts/admin_footer' %>

	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="eng">
	<head>
		<meta charset="utf-8">	
		<title><%= full_title(yield(:title)) %></title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<meta name="Description"
			  content="PLOX: A comic about people who happen to be gamers.">
		<meta name="Author" content="Steve Hamaker">
		<%= csrf_meta_tags %>
		<%= auto_discovery_link_tag :atom, "http://feeds.feedburner.com/plox-comic" %>
		<%= auto_discovery_link_tag :rss,  "http://feeds.feedburner.com/plox-comic" %>

		<!-- Stylesheets -->
		<%= stylesheet_link_tag    "application", media: "all", 
	  													 "data-turbolinks-track" => true %>

	  <%= render 'layouts/shim' %>

	  <!-- Javascripts -->
	  <%= render 'layouts/dfp_ads_js' if Rails.env.production? %>	
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  

	  <!-- Fav and touch icons -->
	  <%= favicon_link_tag 'favicon.ico' %>
	  <%= favicon_link_tag 'favicon.ico', rel: 'apple-touch-icon', type: 'image/png' %>

	</head>
	<body>

		<%= render 'layouts/header' %>

		<section>
			<div class="container wrapper">
						<div class="content">

				      <% flash.each do |key, value| %>
				        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
				      <% end %>
							
							<%= yield %>
						</div>
			</div><!-- /container -->
		</section>
		<%= render 'layouts/bottom_ads' if Rails.env.production? %>
		<%= render 'layouts/footer' %>
		<%= render 'layouts/google_analytics' if Rails.env.production? %>
		<%= render 'layouts/track_outbound_links' if Rails.env.production? %>
	</body>
</html>